/*
 * eHelply SDK - 1.1.113
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.113
 * Contact: support@ehelply.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ehelply.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DetailedMetaGet
 */
public class DetailedMetaGetTest {
    private final DetailedMetaGet model = new DetailedMetaGet();

    /**
     * Model tests for DetailedMetaGet
     */
    @Test
    public void testDetailedMetaGet() {
        // TODO: test DetailedMetaGet
    }

    /**
     * Test the property 'summary'
     */
    @Test
    public void summaryTest() {
        // TODO: test summary
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'summaryHistory'
     */
    @Test
    public void summaryHistoryTest() {
        // TODO: test summaryHistory
    }

    /**
     * Test the property 'descriptionHistory'
     */
    @Test
    public void descriptionHistoryTest() {
        // TODO: test descriptionHistory
    }

}
