/*
 * eHelply SDK - 1.1.86
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.86
 * Contact: support@ehelply.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ehelply.client.model;

import com.ehelply.client.model.Options;
import com.ehelply.client.model.Validations;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for FieldDynamo
 */
public class FieldDynamoTest {
    private final FieldDynamo model = new FieldDynamo();

    /**
     * Model tests for FieldDynamo
     */
    @Test
    public void testFieldDynamo() {
        // TODO: test FieldDynamo
    }

    /**
     * Test the property 'uuid'
     */
    @Test
    public void uuidTest() {
        // TODO: test uuid
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'placeholder'
     */
    @Test
    public void placeholderTest() {
        // TODO: test placeholder
    }

    /**
     * Test the property 'validations'
     */
    @Test
    public void validationsTest() {
        // TODO: test validations
    }

    /**
     * Test the property 'hint'
     */
    @Test
    public void hintTest() {
        // TODO: test hint
    }

    /**
     * Test the property 'icon'
     */
    @Test
    public void iconTest() {
        // TODO: test icon
    }

    /**
     * Test the property 'label'
     */
    @Test
    public void labelTest() {
        // TODO: test label
    }

    /**
     * Test the property 'options'
     */
    @Test
    public void optionsTest() {
        // TODO: test options
    }

}
