/*
 * eHelply SDK - 1.1.105
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.105
 * Contact: support@ehelply.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ehelply.client.model;

import com.ehelply.client.model.History;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for GetProjectInvoiceHistory
 */
public class GetProjectInvoiceHistoryTest {
    private final GetProjectInvoiceHistory model = new GetProjectInvoiceHistory();

    /**
     * Model tests for GetProjectInvoiceHistory
     */
    @Test
    public void testGetProjectInvoiceHistory() {
        // TODO: test GetProjectInvoiceHistory
    }

    /**
     * Test the property 'projectUuid'
     */
    @Test
    public void projectUuidTest() {
        // TODO: test projectUuid
    }

    /**
     * Test the property 'invoiceHistory'
     */
    @Test
    public void invoiceHistoryTest() {
        // TODO: test invoiceHistory
    }

}
