/*
 * eHelply SDK - 1.1.110
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.110
 * Contact: support@ehelply.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ehelply.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MetaChildren
 */
public class MetaChildrenTest {
    private final MetaChildren model = new MetaChildren();

    /**
     * Model tests for MetaChildren
     */
    @Test
    public void testMetaChildren() {
        // TODO: test MetaChildren
    }

    /**
     * Test the property 'childName'
     */
    @Test
    public void childNameTest() {
        // TODO: test childName
    }

    /**
     * Test the property 'childDescription'
     */
    @Test
    public void childDescriptionTest() {
        // TODO: test childDescription
    }

    /**
     * Test the property 'childUuid'
     */
    @Test
    public void childUuidTest() {
        // TODO: test childUuid
    }

}
