/*
 * eHelply SDK - 1.1.96
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.96
 * Contact: support@ehelply.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ehelply.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PaymentMethodResponse
 */
public class PaymentMethodResponseTest {
    private final PaymentMethodResponse model = new PaymentMethodResponse();

    /**
     * Model tests for PaymentMethodResponse
     */
    @Test
    public void testPaymentMethodResponse() {
        // TODO: test PaymentMethodResponse
    }

    /**
     * Test the property 'paymentId'
     */
    @Test
    public void paymentIdTest() {
        // TODO: test paymentId
    }

    /**
     * Test the property 'last4Digits'
     */
    @Test
    public void last4DigitsTest() {
        // TODO: test last4Digits
    }

    /**
     * Test the property 'cardBrand'
     */
    @Test
    public void cardBrandTest() {
        // TODO: test cardBrand
    }

    /**
     * Test the property 'projectUuid'
     */
    @Test
    public void projectUuidTest() {
        // TODO: test projectUuid
    }

}
