/*
 * eHelply SDK - 1.1.88
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.88
 * Contact: support@ehelply.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ehelply.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ProductReturn
 */
public class ProductReturnTest {
    private final ProductReturn model = new ProductReturn();

    /**
     * Model tests for ProductReturn
     */
    @Test
    public void testProductReturn() {
        // TODO: test ProductReturn
    }

    /**
     * Test the property 'metaData'
     */
    @Test
    public void metaDataTest() {
        // TODO: test metaData
    }

    /**
     * Test the property 'collectionUuid'
     */
    @Test
    public void collectionUuidTest() {
        // TODO: test collectionUuid
    }

    /**
     * Test the property 'reviewGroupUuid'
     */
    @Test
    public void reviewGroupUuidTest() {
        // TODO: test reviewGroupUuid
    }

    /**
     * Test the property 'addons'
     */
    @Test
    public void addonsTest() {
        // TODO: test addons
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'quantityForPublic'
     */
    @Test
    public void quantityForPublicTest() {
        // TODO: test quantityForPublic
    }

    /**
     * Test the property 'uuid'
     */
    @Test
    public void uuidTest() {
        // TODO: test uuid
    }

    /**
     * Test the property 'metaUuid'
     */
    @Test
    public void metaUuidTest() {
        // TODO: test metaUuid
    }

    /**
     * Test the property 'projectUuid'
     */
    @Test
    public void projectUuidTest() {
        // TODO: test projectUuid
    }

    /**
     * Test the property 'catalogUuid'
     */
    @Test
    public void catalogUuidTest() {
        // TODO: test catalogUuid
    }

    /**
     * Test the property 'addonList'
     */
    @Test
    public void addonListTest() {
        // TODO: test addonList
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'deletedAt'
     */
    @Test
    public void deletedAtTest() {
        // TODO: test deletedAt
    }

}
