/*
 * eHelply SDK - 1.1.112
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.112
 * Contact: support@ehelply.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ehelply.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ProjectCreditResponse
 */
public class ProjectCreditResponseTest {
    private final ProjectCreditResponse model = new ProjectCreditResponse();

    /**
     * Model tests for ProjectCreditResponse
     */
    @Test
    public void testProjectCreditResponse() {
        // TODO: test ProjectCreditResponse
    }

    /**
     * Test the property 'uuid'
     */
    @Test
    public void uuidTest() {
        // TODO: test uuid
    }

    /**
     * Test the property 'projectUuid'
     */
    @Test
    public void projectUuidTest() {
        // TODO: test projectUuid
    }

    /**
     * Test the property 'creditsGranted'
     */
    @Test
    public void creditsGrantedTest() {
        // TODO: test creditsGranted
    }

    /**
     * Test the property 'creditsConsumed'
     */
    @Test
    public void creditsConsumedTest() {
        // TODO: test creditsConsumed
    }

    /**
     * Test the property 'grantedBy'
     */
    @Test
    public void grantedByTest() {
        // TODO: test grantedBy
    }

    /**
     * Test the property 'grantedReason'
     */
    @Test
    public void grantedReasonTest() {
        // TODO: test grantedReason
    }

    /**
     * Test the property 'grantedAt'
     */
    @Test
    public void grantedAtTest() {
        // TODO: test grantedAt
    }

    /**
     * Test the property 'fullyConsumedAt'
     */
    @Test
    public void fullyConsumedAtTest() {
        // TODO: test fullyConsumedAt
    }

    /**
     * Test the property 'revokedReason'
     */
    @Test
    public void revokedReasonTest() {
        // TODO: test revokedReason
    }

    /**
     * Test the property 'revokedAt'
     */
    @Test
    public void revokedAtTest() {
        // TODO: test revokedAt
    }

}
