/*
 * eHelply SDK - 1.1.113
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.113
 * Contact: support@ehelply.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ehelply.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for StaffResponse
 */
public class StaffResponseTest {
    private final StaffResponse model = new StaffResponse();

    /**
     * Model tests for StaffResponse
     */
    @Test
    public void testStaffResponse() {
        // TODO: test StaffResponse
    }

    /**
     * Test the property 'entityUuid'
     */
    @Test
    public void entityUuidTest() {
        // TODO: test entityUuid
    }

    /**
     * Test the property 'projectUuid'
     */
    @Test
    public void projectUuidTest() {
        // TODO: test projectUuid
    }

    /**
     * Test the property 'scheduleUuid'
     */
    @Test
    public void scheduleUuidTest() {
        // TODO: test scheduleUuid
    }

    /**
     * Test the property 'catalogUuid'
     */
    @Test
    public void catalogUuidTest() {
        // TODO: test catalogUuid
    }

    /**
     * Test the property 'reviewGroupUuid'
     */
    @Test
    public void reviewGroupUuidTest() {
        // TODO: test reviewGroupUuid
    }

    /**
     * Test the property 'uuid'
     */
    @Test
    public void uuidTest() {
        // TODO: test uuid
    }

    /**
     * Test the property 'entity'
     */
    @Test
    public void entityTest() {
        // TODO: test entity
    }

    /**
     * Test the property 'place'
     */
    @Test
    public void placeTest() {
        // TODO: test place
    }

    /**
     * Test the property 'placeRoles'
     */
    @Test
    public void placeRolesTest() {
        // TODO: test placeRoles
    }

    /**
     * Test the property 'company'
     */
    @Test
    public void companyTest() {
        // TODO: test company
    }

    /**
     * Test the property 'companyRoles'
     */
    @Test
    public void companyRolesTest() {
        // TODO: test companyRoles
    }

    /**
     * Test the property 'schedule'
     */
    @Test
    public void scheduleTest() {
        // TODO: test schedule
    }

    /**
     * Test the property 'catalog'
     */
    @Test
    public void catalogTest() {
        // TODO: test catalog
    }

    /**
     * Test the property 'reviews'
     */
    @Test
    public void reviewsTest() {
        // TODO: test reviews
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'deletedAt'
     */
    @Test
    public void deletedAtTest() {
        // TODO: test deletedAt
    }

}
